# eslintrc file
#
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  # Extend prettier will make eslint only checking for errors in the code and not formating
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - ".css"
    - ".svg"
  project:
    - "./tsconfig.json"

plugins:
  - "@typescript-eslint"

